### ISSUE TITLE
node 20

### ISSUE THREAD

**Issue by davhdavh** [lasith-kg/dispatch-workflow#112]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: lasith-kg/dispatch-workflow@692cec720c2d07367b512c5f8668e33c3d8f2f13. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by davhdavh** [comment]
I assume it is https://github.com/lasith-kg/dispatch-workflow/blob/692cec720c2d07367b512c5f8668e33c3d8f2f13/action.yml#L51
since the deps include node20 for the build

**Comment by lasith-kg** [comment]
No worries. Let's get this supporting Node v20

**Comment by lasith-kg** [comment]
Hey @davhdavh , I'm having issues with the library I use to release the GitHub Actions `release-it`. I'll investigate this further over the weekend

**Comment by davhdavh** [comment]
No worries, I'm guessing you have a couple of weeks/months more before they actually remove support.

**Comment by lasith-kg** [comment]
I'm closing this issue. I have tried the action in some personal workflows and did not run into any issues. Thank you @davhdavh! Feel free to give this repository a ⭐ if you had a good experience! It really helps me out
