### ISSUE TITLE
Workflow does not exists or does not have a dispatch trigger in this branch

### ISSUE THREAD

**Issue by lfoppiano** [lasith-kg/dispatch-workflow#152]
Hi, I've set up a github action that allow manual build of specific branches but when I select the branch which is not a master/main branch, I get this message: 

<img width="328" alt="image" src="https://github.com/lasith-kg/dispatch-workflow/assets/15426/f46cc490-b814-4f8f-bdfc-ca34cd14eabf">

Now, as usually happens, at the moment I open an issue, I get a solution in my head. Does this indicate that in the target branch, the workflow files are not available? This might be actually my case at the moment as the modification to the github actions was only in the master/main branch.

**Comment by lfoppiano** [comment]
I think this is the reason. So merge master into the target branch would solve this issue. 
Perhaps a better wording or a more link that directly discuss the issue would clarify the message.

**Comment by lasith-kg** [comment]
Hey! Sorry I'm not sure if this issue is something that is relevant to the GitHub Action, but rather the GitHub UI.

I've had issues before with the GitHub UI where I create a workflow in a feature branch, but it is not visible until I merge it into the main branch.

**Comment by lfoppiano** [comment]
@lasith-kg there are so many components on the github actions, that I was not really sure where to post this issue. Feel free to "forward" it in the more appropriate project. 

> I've had issues before with the GitHub UI where I create a workflow in a feature branch, but it is not visible until I merge it into the main branch.

I vaguely remember I could do test new changes in the action workflow in separate branch features, but I'm not totally sure about it...
